channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.2.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.24.3
  - packaging==23.0
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.3.0
  - scipy==1.10.1
name: mlflow-env
